---

    - name: "Create F5 HA AV Set in Azure - *** This will take 10 minutes so get a drink ****"
      azure_rm_deployment:
        state: present
        client_id: '{{client_id}}'
        secret: '{{secret}}'
        subscription_id: '{{subscription_id}}'
        tenant: '{{tenant}}'
        resource_group_name: '{{resource_group_name}}'
        parameters:
                adminPassword:
                    value: '{{adminPassword}}'
                dnsLabel:
                    value: '{{dnsLabel}}'
                numberOfExternalIps:
                    value: 2
                imageName:
                    value: '{{imageName}}'
                licenseKey1:
                    value: '{{licenseKey1}}'
                licenseKey2:
                    value: '{{licenseKey2}}'
                tenantId:
                    value: '{{tenant}}'
                clientid:
                    value: '{{client_id}}'
                servicePrincipalSecret:
                    value: '{{secret}}'

        template_link: 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/v5.0.0.0/supported/cluster/failover-api/new_stack/BYOL/azuredeploy.json'
        #template_link: 'https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/cluster/failover-api/existing_stack/PAYG/azuredeploy.json'
