resource_group_name: "AVSet"
name_server1: "8.8.8.8"
name_server2: "4.4.4.4"
search_domain1: "local.com"
search_domain2: "localhost"
ntp_server1: "0.ca.pool.ntp.org"
ntp_server2: "1.ca.pool.ntp.org"
ntp_server3: "2.ca.pool.ntp.org"
timezone: "Canada/Saskatchewan"
AZURE_RESOURCE_GROUPS: "{{ resource_group_name }}"
dnsLabel: dens
server: "{{ bigip }}"
modules:
  - {name: asm, level: nominal}
  - {name: apm, level: nominal}

mgmt_rules:
  - name: Allow_SSH
    protocol: Tcp
    source_address_prefix: "{{ my_ip }}"
    destination_port_range: 22
    access: Allow
    direction: Inbound
    priority: 100
  - name: Allow_HTTPS
    protocol: Tcp
    source_address_prefix: "{{ my_ip }}"
    destination_port_range: 443
    access: Allow
    direction: Inbound
    priority: 101

ext_rules:
  - name: Allow_80
    protocol: Tcp
    source_address_prefix: "{{ my_ip }}"
    destination_port_range: 80
    access: Allow
    direction: Inbound
    priority: 100
  - name: Allow_443
    protocol: Tcp
    source_address_prefix: "{{ my_ip }}"
    destination_port_range: 443
    access: Allow
    direction: Inbound
    priority: 101
